"""Voice pipeline events."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from humanoid_robot.domain.knowledge import Citation
from humanoid_robot.domain.shared import SessionId, UtteranceId
from humanoid_robot.domain.voice import Language
from humanoid_robot.events.base import BaseEvent


class SpeechDetected(BaseEvent):
    """Silero VAD detected speech in the mic stream."""

    subject: ClassVar[str] = "speech.vad.detected"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    start_ms: int = Field(ge=0)
    end_ms: int = Field(ge=0)
    energy_db: float


class WakeWordTriggered(BaseEvent):
    """The configured wake word was recognised."""

    subject: ClassVar[str] = "speech.wake_word.triggered"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    word: str
    confidence: float = Field(ge=0.0, le=1.0)


class AsrPartial(BaseEvent):
    """ASR partial hypothesis for a live utterance."""

    subject: ClassVar[str] = "asr.partial"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    utterance_id: UtteranceId
    text: str
    stable_prefix_len: int = Field(ge=0)


class AsrFinal(BaseEvent):
    """ASR final result for an utterance."""

    subject: ClassVar[str] = "asr.final"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    utterance_id: UtteranceId
    text: str
    language: Language
    confidence: float = Field(ge=0.0, le=1.0)


class LlmAnswerToken(BaseEvent):
    """A single delta from a streaming LLM answer.

    Producers are LLM adapters that support token-level streaming (see
    ``LlmPort.stream``).  The final ``LlmAnswer`` is still emitted after
    the last token so consumers that only care about the completed
    answer keep working unchanged.
    """

    subject: ClassVar[str] = "llm.answer.token"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    sequence: int = Field(ge=0)
    delta_text: str
    is_final: bool = False


class LlmAnswer(BaseEvent):
    """A grounded answer generated by the LLM."""

    subject: ClassVar[str] = "llm.answer"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    text: str
    language: Language = Language.RU
    citations: tuple[Citation, ...]
    confidence: float = Field(ge=0.0, le=1.0)


class LlmRejected(BaseEvent):
    """The pipeline refused to answer (retrieval or grounding failure)."""

    subject: ClassVar[str] = "llm.rejected"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    reason: str
    fallback_text: str | None = None


class LlmConfigChanged(BaseEvent):
    """The operator switched the LLM backend (local ⇄ cloud) from the app.

    Carries NO secrets — consumers fetch the full config (incl. api key)
    from core over HTTP.
    """

    subject: ClassVar[str] = "llm.config.changed"
    schema_version: ClassVar[int] = 1

    mode: str  # "local" | "cloud"
    model: str = ""


class VoiceInterrupt(BaseEvent):
    """Operator asked the robot to stop talking right now (UI stop button)."""

    subject: ClassVar[str] = "voice.interrupt"
    schema_version: ClassVar[int] = 1

    reason: str = "operator"


class TtsSynthesisStarted(BaseEvent):
    """TTS started producing audio for an utterance."""

    subject: ClassVar[str] = "tts.synth.started"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    utterance_id: UtteranceId


class TtsSynthesisFinished(BaseEvent):
    """TTS finished emitting audio for an utterance."""

    subject: ClassVar[str] = "tts.synth.finished"
    schema_version: ClassVar[int] = 1

    session_id: SessionId
    utterance_id: UtteranceId
    duration_ms: int = Field(ge=0)
